name: Sync fork to personal repo

on:
  push:
    branches:
      - main   # 배포 기준 브랜치

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout org repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to personal fork
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git remote add fork https://x-access-token:${{ secrets.PERSONAL_REPO_TOKEN }}@github.com/sungahChooo/DiggIndie-FE.git

          git push fork dev --force
